### ISSUE TITLE
说明实在是太……

### ISSUE THREAD

**Issue by wycstc353** [ben0oil1/GPT-SoVITS-Server#11]
D:\asdasd\AI\GPT-SoVITS-Server-main\GPT-SoVITS-Server-main>python server.py
DirectML可用，将使用DirectML进行推理加速。
设备名称: NVIDIA GeForce GTX 1650
Traceback (most recent call last):
  File "D:\asdasd\AI\GPT-SoVITS-Server-main\GPT-SoVITS-Server-main\server.py", line 71, in <module>
    tokenizer = AutoTokenizer.from_pretrained(bert_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wyc\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\models\auto\tokenization_auto.py", line 926, in from_pretrained
    return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wyc\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\tokenization_utils_base.py", line 2200, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for './pretrained/chinese-roberta-wwm-ext-large'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure './pretrained/chinese-roberta-wwm-ext-large' is the correct path to a directory containing all relevant files for a RobertaTokenizerFast tokenizer.
好不容易把依赖装完了，还是报错，我现在东西是这样放得
![image](https://github.com/user-attachments/assets/d2f0ec45-784f-416c-909b-43a092522e8b)
![image](https://github.com/user-attachments/assets/7706a5f2-da04-49ad-a38e-545de4e99eac)

**Comment by ben0oil1** [comment]
你把脚本打开，把预训练模型的存放路径直接硬编码上去，试试
